### ISSUE TITLE
Implement Architectural Pattern in iOS

### ISSUE THREAD

**Issue by jfpatino01** [ISIS3510-Seccion-3-Grupo-32/SafeGo_iOS#5]
We will use the MVVM to do so. Based on the prototype and defined diagramas.

**Comment by JMarts32** [comment]
The structure is already created. There arre three folders under the name of Model, View and ViewModels.

**Comment by JMarts32** [comment]
Observer design pattern implemented. Xcode version

**Comment by JMarts32** [comment]
Factory design pattern implemented in the class SGButtonLR.swift
